#!/bin/bash/env bash
source ./get-environment
function installJava() {
  #如果有错误继续执行
  set +e
  isinstalljava="-b"
  isinstalljava=false
  $(java -version)
  set -e
  if [ $? -ne 0 ]; then
    isinstalljava=true
  else
    #  获取java版本
    javaversion=$(java -version 2>&1 | awk 'NR==1{gsub(/"/,"");print $3}')
    echo java version $javaversion
    #从右向左截取最后一个.的开始截取，获取大版本号
    large=${javaversion%%.*}
    #从左向右截取去除大版本号
    javaversion=${javaversion#*.}
    echo java 大版本号 $large
    #从右向左截取最后一个.的开始截取，获取小版本号
    mini=${javaversion%%.*}
    echo java 小版本号 $mini
    #判断是否大于1.8
    if [ $large -gt 1 ]; then
      isinstalljava=false
    else
      if [ $mini -ge 8 ]; then
        isinstalljava=false
      else
        isinstalljava=true
      fi
    fi

  fi

  echo 是否需要安装:$isinstalljava
  #  判断是否安装了java
  isinstalljava=true
  if [ $isinstalljava = true ]; then
    echo test
  fi
}

echo weclome
installJava
echo $systemArchitecture
